#!/usr/bin/env python3
"""
Generate a flake.nix for the NUR combined workspace from repos.json.

Reads repos.json (repo URLs) and repos.json.lock (locked revisions)
and produces a flake.nix that:
  - Lists every NUR repo as a flake input with locked revision
  - Evaluates each repo using the existing evalRepo.nix / repoSource.nix infra
  - Provides per-repo and combined package outputs

Usage:
  python3 generate_nur_flake.py \
    --repos-json /path/to/repos.json \
    --lock-json /path/to/repos.json.lock \
    --output /path/to/flake.nix

Adapted from cargo-vendormod's flake-generation pattern.
"""

import argparse
import json
import os
import sys
from typing import Any


def load_json(path: str) -> Any:
    with open(path) as f:
        return json.load(f)


def sanitize_name(name: str) -> str:
    """Sanitize a repo name for use as a Nix attribute name."""
    return name.replace("-", "_").replace(".", "_").replace("/", "_")


def is_github_url(url: str) -> bool:
    return url.startswith("https://github.com/") or url.startswith("git+https://github.com/")


def is_gitlab_url(url: str) -> bool:
    return url.startswith("https://gitlab.com/") or "gitlab" in url.lower()


def is_sourcehut_url(url: str) -> bool:
    return "git.sr.ht" in url or "sr.ht" in url


def to_flake_input_url(url: str, rev: str | None = None) -> str:
    """Convert a repo URL to a Nix flake input URL, optionally locking to a revision."""
    if is_github_url(url):
        # Strip trailing .git, protocol prefix for cleaner URLs
        clean = url.replace("git+https://", "https://").replace(".git", "")
        if rev:
            return f"github:{clean.removeprefix('https://github.com/')}/{rev}"
        return f"github:{clean.removeprefix('https://github.com/')}"
    elif "gitlab" in url.lower() or "gitlab.com" in url:
        # GitLab URLs with rev locking
        clean = url.replace(".git", "")
        if rev:
            return f"git+{clean}?rev={rev}"
        return f"git+{clean}"
    else:
        # Generic git URLs
        clean = url.replace(".git", "")
        if rev:
            return f"git+{clean}?rev={rev}"
        return f"git+{clean}"


def generate_flake_nix(repos: dict, locked: dict) -> str:
    """Generate the complete flake.nix content."""
    
    # ── Build per-repo input specs ──────────────────────────────────────
    input_entries = []
    repo_by_input = {}
    
    for name, attr in sorted(repos.items()):
        sname = sanitize_name(name)
        url = attr["url"]
        rev = locked.get(name, {}).get("rev")
        
        input_url = to_flake_input_url(url, rev)
        input_entries.append((sname, input_url))
        repo_by_input[sname] = name
    
    # ── Templates ──────────────────────────────────────────────────────
    input_lines = "\n".join(
        f'    {sname}.url = "{url}";'
        for sname, url in input_entries
    )
    
    # ── Build the flake.nix ────────────────────────────────────────────
    flake = f'''# THIS FILE IS AUTO-GENERATED by generate_nur_flake.py
# DO NOT EDIT MANUALLY — regenerate with:
#   python3 generate_nur_flake.py --repos-json repos.json --lock-json repos.json.lock --output flake.nix
#
# Generated from cargo-vendormod flake-generation pattern.
# Contains {len(repos)} NUR repository inputs.

{{
  description = "NUR Combined — every nix-community NUR repository as a flake";

  inputs = {{
    # Pinned nixpkgs for reproducible evaluation
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    # ── {len(repos)} NUR repository inputs ──
{input_lines}
  }};

  outputs =
    {{ self, nixpkgs
     , {', '.join(sname for sname, _ in input_entries)}
     }}:
    let
      # Systems to build for
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);

      # Helper: derive a system-specific pkgs from nixpkgs
      pkgsFor = system: import nixpkgs {{ inherit system; }};

      # ── Per-repo evaluation ──────────────────────────────────────────
      # Each NUR repo gets evaluated with the standard NUR pattern:
      #   import default.nix {{ pkgs = ...; }}
      #
      # Some repos provide flake.nix instead — we detect and handle both.
      evalRepo = name: input:
        let
          # Check if the repo has a flake.nix (flake-enabled NUR repo)
          hasFlake = builtins.pathExists (input + "/flake.nix");
          # If flake, use its packages; otherwise use the default.nix pattern
          result = if hasFlake
            then input.packages
            else (import (input + "/default.nix") {{ }});
        in result;

      # ── Per-repo package sets ────────────────────────────────────────
      repoPackages = {{
''';
    
    # Add per-repo package entries (as Nix comments/examples for reference)
    # Actually, let's put them as attributes in the output
    repo_attr_lines = []
    for sname, name in sorted(repo_by_input.items()):
        safe_comment = name.replace("*/", "* /")
        repo_attr_lines.append(
            f'        # {safe_comment}\n'
            f'        {sname} = evalRepo "{name}" {sname};'
        )
    
    flake += "\n".join(repo_attr_lines)
    
    flake += f'''
      }};

      # ── Combined package set (union of all repos) ───────────────────
      # Collects every package from every NUR repo into a flat attribute set.
      # Conflicts are prefixed with "<repo-name>-".
      allPackages = nixpkgs.lib.foldl
        (acc: repoName:
          let
            pkgs = repoPackages.${{repoName}};
            prefixed = nixpkgs.lib.mapAttrs'
              (name: value: {{
                name = "${{repoName}}-''${{name}}";
                inherit value;
              }})
              (builtins.removeAttrs pkgs [ "overlays" "modules" "nixosModules" "checks" "devShells" "formatter"]);
          in acc // prefixed
        )
        {{ }}
        (builtins.attrNames repoPackages);
    in
    {{
      # Per-repo packages — use as: nix build .#<repo-name>.<package>
      inherit repoPackages;

      # Flat combined packages (repo-name-prefixed) — use as: nix build .#mic92-hello-nur
      packages = forAllSystems (system: allPackages);

      # Legacy NUR-compatible top-level (for nix-env -f default.nix)
      legacyPackages = forAllSystems (system: repoPackages);

      # Apps: generate a graph of all repo packages
      apps = forAllSystems (system: {{
        list-repos = {{
          type = "app";
          program = "${{nixpkgs.legacyPackages.${{system}}.coreutils}}/bin/echo";
        }};
      }});
    }};
}}
'''
    return flake


def main():
    parser = argparse.ArgumentParser(
        description="Generate flake.nix for NUR combined workspace from repos.json"
    )
    parser.add_argument(
        "--repos-json",
        default="repos.json",
        help="Path to repos.json (default: ./repos.json)",
    )
    parser.add_argument(
        "--lock-json",
        default="repos.json.lock",
        help="Path to repos.json.lock (default: ./repos.json.lock)",
    )
    parser.add_argument(
        "--output",
        default="flake.nix",
        help="Output path for generated flake.nix (default: ./flake.nix)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check existing flake.nix without overwriting",
    )
    
    args = parser.parse_args()
    
    if not os.path.exists(args.repos_json):
        print(f"Error: {args.repos_json} not found", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(args.lock_json):
        print(f"Error: {args.lock_json} not found", file=sys.stderr)
        sys.exit(1)
    
    repos_data = load_json(args.repos_json)
    lock_data = load_json(args.lock_json)
    
    repos = repos_data.get("repos", repos_data)
    locked = lock_data.get("repos", lock_data)
    
    flake_content = generate_flake_nix(repos, locked)
    
    if args.check:
        if os.path.exists(args.output):
            existing = open(args.output).read()
            if existing == flake_content:
                print(f"✓ {args.output} is up to date")
                return
            else:
                print(f"✗ {args.output} is out of date — regenerate needed")
                print(f"  Run: python3 {__file__} --repos-json {args.repos_json} --lock-json {args.lock_json} --output {args.output}")
                sys.exit(1)
        else:
            print(f"✗ {args.output} does not exist — generate it")
            print(f"  Run: python3 {__file__} --repos-json {args.repos_json} --lock-json {args.lock_json} --output {args.output}")
            sys.exit(1)
    
    # Write output
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(flake_content)
    
    repo_count = len(repos)
    print(f"✓ Generated {args.output} with {repo_count} repos")
    print(f"  Run: nix flake check --impure  # to validate")


if __name__ == "__main__":
    main()
