# THIS FILE IS AUTO-GENERATED by cargo-vendormod (Python)
# DO NOT EDIT MANUALLY
#
# Package: cbor2

{
  description = "cbor2 - Python package";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        real_src = ./.;
        python = pkgs.python3;
        buildPythonPackage = python.pkgs.buildPythonPackage;
      in
      {
        packages = {
          default = pkgs.callPackage ./package.nix {
            inherit buildPythonPackage;
            src = real_src;
          };
          cbor2 = self.packages.${system}.default;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [ python python.pkgs.pip python.pkgs.setuptools ];
        };
      }
    );
}
