[package]
name = "graphcmd"
version = "0.1.0"
edition = "2021"
description = "Decl lattice node: GraphCmd"

[dependencies]
analyzeargs = { path = "../analyzeargs" }
buildargs = { path = "../buildargs" }
visualizeargs = { path = "../visualizeargs" }
partitionargs = { path = "../partitionargs" }
path = { path = "../path" }
path = { path = "../path" }
