[package]
name = "vendoringsubcmd"
version = "0.1.0"
edition = "2021"
description = "Decl lattice node: VendoringSubCmd"

[dependencies]
vendoringcmd = { path = "../vendoringcmd" }
path = { path = "../path" }
path = { path = "../path" }
command = { path = "../command" }
command = { path = "../command" }
