[package]
name = "order"
version = "0.1.0"
edition = "2021"
description = "Decl lattice node: order"

[dependencies]
sporadicgroup = { path = "../sporadicgroup" }
atlasconfig = { path = "../atlasconfig" }
twistedlietype = { path = "../twistedlietype" }
classicallietype = { path = "../classicallietype" }
atlasrenderer = { path = "../atlasrenderer" }
atlasrenderer = { path = "../atlasrenderer" }
n = { path = "../n" }
groups = { path = "../groups" }
groupfamily = { path = "../groupfamily" }
groupatlas = { path = "../groupatlas" }
groupatlas = { path = "../groupatlas" }
