# THIS FILE IS AUTO-GENERATED by cargo-vendormod (Go)
# DO NOT EDIT MANUALLY
#
# Module: github.com/ipfs/go-ipld-cbor

{
  description = "github.com/ipfs/go-ipld-cbor - Go module";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        real_src = ./.;
      in
      {
        packages = {
          default = pkgs.callPackage ./package.nix { src = real_src; };
          github.com/ipfs/go-ipld-cbor = self.packages.${system}.default;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [ go gopls gotools ];
        };
      }
    );
}
