[package]
name = "goal"
version = "0.1.0"
edition = "2021"
description = "Decl lattice node: Goal"

[dependencies]
dmaicphase = { path = "../dmaicphase" }
crqstatus = { path = "../crqstatus" }
id = { path = "../id" }
name = { path = "../name" }
sixsigmametrics = { path = "../sixsigmametrics" }
sixsigmametrics = { path = "../sixsigmametrics" }
