# THIS FILE IS AUTO-GENERATED by cargo-vendormod (JavaScript)
# DO NOT EDIT MANUALLY
#
# Package: specs

{
  description = "specs - JavaScript package";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        real_src = ./.;
      in
      {
        packages = {
          default = pkgs.callPackage ./package.nix { src = real_src; };
          specs = self.packages.${system}.default;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [ nodejs nodePackages.npm ];
        };
      }
    );
}
