# THIS FILE IS AUTO-GENERATED by cargo-vendormod (C/C++)
# DO NOT EDIT MANUALLY
#
# Project: gatewayd-startos

{
  description = "gatewayd-startos - C/C++ project";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        real_src = ./.;
      in
      {
        packages = {
          default = pkgs.callPackage ./package.nix { src = real_src; };
          gatewayd-startos = self.packages.${system}.default;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [ gcc pkg-config ];
        };
      }
    );
}
