//! # Multi-Language Flake Generator
//!
//! Generates `flake.nix` files for projects in languages other than Rust.
//! Each generator produces a Nix flake that builds the project using the
//! appropriate Nixpkgs build infrastructure.
//!
//! ## Supported Languages
//!
//! - **Go**: `buildGoModule` with `vendorHash` and `proxyVendor`
//! - **Python**: `buildPythonPackage` with `pyproject` / `maturin` build hooks
//! - **C/C++**: `stdenv.mkDerivation` with CMake or Make
//! - **JavaScript**: `buildNpmPackage` with `npmDeps`
//! - **Java**: `stdenv.mkDerivation` with Maven/Gradle caching
//! - **Lean4**: `lean4-nix` dependency template with `lean --make`

use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use crate::crate_flake::{FlakeSource, FlakeStyle};

// ── Go flake generation ─────────────────────────────────────────────────

/// Generate a Go flake: `buildGoModule` with `vendorHash` and `proxyVendor`.
///
/// Output: `<output_dir>/flakes/<module_name>/flake.nix` + `package.nix`
pub fn generate_go_flake(
    project_dir: &Path,
    output_dir: &Path,
    _style: FlakeStyle,
    source: &FlakeSource,
) -> Result<usize> {
    let module_name = extract_go_module_name(project_dir).unwrap_or_else(|| "go-module".to_string());
    let flake_dir = output_dir.join("flakes").join(&module_name);
    fs::create_dir_all(&flake_dir)
        .with_context(|| format!("Failed to create flake dir: {}", flake_dir.display()))?;

    let (src_input, src_attr) = match source {
        FlakeSource::LocalDir => (String::new(), String::new()),
        FlakeSource::GitMirror { mirror_path, display: _ } => {
            let input = format!(
                r#"    src = {{
      url = "git+file://{mirror}";
      flake = false;
    }};
"#,
                mirror = mirror_path.display()
            );
            (input, "src".to_string())
        }
    };

    let params = if src_attr.is_empty() {
        "{ self, nixpkgs, flake-utils }".to_string()
    } else {
        format!("{{ self, nixpkgs, flake-utils, {src_attr} }}")
    };

    let src_reference = if src_attr.is_empty() {
        "./.".to_string()
    } else {
        format!("{src_attr}")
    };

    let package_nix = format!(
        r#"{{ pkgs, lib, src ? ./., ... }}:

pkgs.buildGoModule {{
  pname = "{name}";
  version = "0.1.0";
  inherit src;
  vendorHash = null;   # set to "sha256-..." after first build
  proxyVendor = true;  # fetch from Go proxy instead of vendoring
  doCheck = false;
}}
"#,
        name = module_name
    );

    let flake_nix = format!(
        r#"# THIS FILE IS AUTO-GENERATED by cargo-vendormod (Go)
# DO NOT EDIT MANUALLY
#
# Module: {name}

{{
  description = "{name} - Go module";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
{src_input}  }};

  outputs =
    {params}:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {{ inherit system; }};
        real_src = {src_reference};
      in
      {{
        packages = {{
          default = pkgs.callPackage ./package.nix {{ src = real_src; }};
          {name} = self.packages.${{system}}.default;
        }};

        devShells.default = pkgs.mkShell {{
          buildInputs = with pkgs; [ go gopls gotools ];
        }};
      }}
    );
}}
"#,
        name = module_name,
        src_input = src_input,
        params = params,
        src_reference = src_reference,
    );

    fs::write(flake_dir.join("flake.nix"), &flake_nix)
        .with_context(|| format!("Failed to write flake.nix for {}", module_name))?;
    fs::write(flake_dir.join("package.nix"), &package_nix)
        .with_context(|| format!("Failed to write package.nix for {}", module_name))?;

    Ok(2)
}

fn extract_go_module_name(project_dir: &Path) -> Option<String> {
    let go_mod = project_dir.join("go.mod");
    if !go_mod.exists() {
        return None;
    }
    let content = fs::read_to_string(&go_mod).ok()?;
    content.lines().next().and_then(|line| {
        let line = line.trim();
        if line.starts_with("module ") {
            Some(line.trim_start_matches("module ").trim().to_string())
        } else {
            None
        }
    })
}

// ── Python flake generation ─────────────────────────────────────────────

/// Generate a Python flake using `buildPythonPackage`.
///
/// Detects `pyproject.toml` vs `setup.py` setup and selects the appropriate
/// build backend (maturin, setuptools, etc.).
pub fn generate_python_flake(
    project_dir: &Path,
    output_dir: &Path,
    _style: FlakeStyle,
    source: &FlakeSource,
) -> Result<usize> {
    let project_name = extract_python_project_name(project_dir).unwrap_or_else(|| "python-package".to_string());
    let flake_dir = output_dir.join("flakes").join(&project_name);
    fs::create_dir_all(&flake_dir)
        .with_context(|| format!("Failed to create flake dir: {}", flake_dir.display()))?;

    let has_pyproject = project_dir.join("pyproject.toml").exists();
    let has_maturin = has_pyproject && has_maturin_build(project_dir);

    let (build_inputs, build_phase, format_attr) = if has_maturin {
        (
            "maturin",
            r#"    buildPhase = ''
      maturin build --release --out dist
    '';
    installPhase = ''
      pip install --no-index --find-links dist ${{pname}} --prefix=$out
    '';"#,
            "format = \"pyproject\";",
        )
    } else {
        (
            "setuptools",
            r#"    # default build/install phases"#,
            "format = \"setuptools\";",
        )
    };

    let (src_input, src_attr) = match source {
        FlakeSource::LocalDir => (String::new(), String::new()),
        FlakeSource::GitMirror { mirror_path, display: _ } => {
            let input = format!(
                r#"    src = {{
      url = "git+file://{mirror}";
      flake = false;
    }};
"#,
                mirror = mirror_path.display()
            );
            (input, "src".to_string())
        }
    };

    let params = if src_attr.is_empty() {
        "{ self, nixpkgs, flake-utils }".to_string()
    } else {
        format!("{{ self, nixpkgs, flake-utils, {src_attr} }}")
    };

    let src_reference = if src_attr.is_empty() {
        "./.".to_string()
    } else {
        format!("{src_attr}")
    };

    let package_nix = format!(
        r#"{{ pkgs, lib, src ? ./., buildPythonPackage, ... }}:

buildPythonPackage {{
  pname = "{name}";
  version = "0.1.0";
  inherit src;
  {format_attr}
  pyproject = true;

  nativeBuildInputs = with pkgs; [ {build_inputs} ];

{build_phase}

  doCheck = false;
}}
"#,
        name = project_name,
        format_attr = format_attr,
        build_inputs = build_inputs,
        build_phase = build_phase,
    );

    let flake_nix = format!(
        r#"# THIS FILE IS AUTO-GENERATED by cargo-vendormod (Python)
# DO NOT EDIT MANUALLY
#
# Package: {name}

{{
  description = "{name} - Python package";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
{src_input}  }};

  outputs =
    {params}:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {{ inherit system; }};
        real_src = {src_reference};
        python = pkgs.python3;
        buildPythonPackage = python.pkgs.buildPythonPackage;
      in
      {{
        packages = {{
          default = pkgs.callPackage ./package.nix {{
            inherit buildPythonPackage;
            src = real_src;
          }};
          {name} = self.packages.${{system}}.default;
        }};

        devShells.default = pkgs.mkShell {{
          buildInputs = with pkgs; [ python python.pkgs.pip python.pkgs.setuptools ];
        }};
      }}
    );
}}
"#,
        name = project_name,
        src_input = src_input,
        params = params,
        src_reference = src_reference,
    );

    fs::write(flake_dir.join("flake.nix"), &flake_nix)
        .with_context(|| format!("Failed to write flake.nix for {}", project_name))?;
    fs::write(flake_dir.join("package.nix"), &package_nix)
        .with_context(|| format!("Failed to write package.nix for {}", project_name))?;

    Ok(2)
}

fn extract_python_project_name(project_dir: &Path) -> Option<String> {
    // Try pyproject.toml first
    let pyproject = project_dir.join("pyproject.toml");
    if pyproject.exists() {
        if let Ok(content) = fs::read_to_string(&pyproject) {
            if let Some(line) = content.lines().find(|l| l.trim().starts_with("name = \"")) {
                let name = line.trim().trim_start_matches("name = \"").trim_end_matches('"');
                return Some(name.to_string());
            }
        }
    }
    // Try setup.cfg
    let setup_cfg = project_dir.join("setup.cfg");
    if setup_cfg.exists() {
        if let Ok(content) = fs::read_to_string(&setup_cfg) {
            if let Some(line) = content.lines().find(|l| l.trim().starts_with("name = ")) {
                let name = line.trim().trim_start_matches("name = ");
                return Some(name.to_string());
            }
        }
    }
    None
}

fn has_maturin_build(project_dir: &Path) -> bool {
    let pyproject = project_dir.join("pyproject.toml");
    if !pyproject.exists() {
        return false;
    }
    if let Ok(content) = fs::read_to_string(&pyproject) {
        content.contains("maturin")
    } else {
        false
    }
}

// ── C/C++ flake generation ──────────────────────────────────────────────

/// Generate a C/C++ flake using `stdenv.mkDerivation`.
///
/// Detects CMake vs Make and generates the appropriate build recipe.
pub fn generate_c_flake(
    project_dir: &Path,
    output_dir: &Path,
    _style: FlakeStyle,
    source: &FlakeSource,
) -> Result<usize> {
    let project_name = project_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("c-project");
    let flake_dir = output_dir.join("flakes").join(&project_name);
    fs::create_dir_all(&flake_dir)
        .with_context(|| format!("Failed to create flake dir: {}", flake_dir.display()))?;

    let has_cmake = project_dir.join("CMakeLists.txt").exists();
    let (native_inputs, build_phase) = if has_cmake {
        (
            "cmake pkg-config",
            r#"    buildPhase = ''
      cmake -DCMAKE_INSTALL_PREFIX=$out ..
      make
    '';
    installPhase = ''
      make install
    '';"#,
        )
    } else {
        (
            "pkg-config",
            r#"    buildPhase = ''
      make
    '';
    installPhase = ''
      make install
    '';"#,
        )
    };

    let (src_input, src_attr) = match source {
        FlakeSource::LocalDir => (String::new(), String::new()),
        FlakeSource::GitMirror { mirror_path, display: _ } => {
            let input = format!(
                r#"    src = {{
      url = "git+file://{mirror}";
      flake = false;
    }};
"#,
                mirror = mirror_path.display()
            );
            (input, "src".to_string())
        }
    };

    let params = if src_attr.is_empty() {
        "{ self, nixpkgs, flake-utils }".to_string()
    } else {
        format!("{{ self, nixpkgs, flake-utils, {src_attr} }}")
    };

    let src_reference = if src_attr.is_empty() {
        "./.".to_string()
    } else {
        format!("{src_attr}")
    };

    let package_nix = format!(
        r#"{{ pkgs, lib, src ? ./., ... }}:

pkgs.stdenv.mkDerivation {{
  pname = "{name}";
  version = "0.1.0";
  inherit src;

  nativeBuildInputs = with pkgs; [ {native_inputs} ];
  buildInputs = with pkgs; [ ];

{build_phase}

  doCheck = false;
}}
"#,
        name = project_name,
        native_inputs = native_inputs,
        build_phase = build_phase,
    );

    let flake_nix = format!(
        r#"# THIS FILE IS AUTO-GENERATED by cargo-vendormod (C/C++)
# DO NOT EDIT MANUALLY
#
# Project: {name}

{{
  description = "{name} - C/C++ project";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
{src_input}  }};

  outputs =
    {params}:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {{ inherit system; }};
        real_src = {src_reference};
      in
      {{
        packages = {{
          default = pkgs.callPackage ./package.nix {{ src = real_src; }};
          {name} = self.packages.${{system}}.default;
        }};

        devShells.default = pkgs.mkShell {{
          buildInputs = with pkgs; [ gcc pkg-config ];
        }};
      }}
    );
}}
"#,
        name = project_name,
        src_input = src_input,
        params = params,
        src_reference = src_reference,
    );

    fs::write(flake_dir.join("flake.nix"), &flake_nix)
        .with_context(|| format!("Failed to write flake.nix for {}", project_name))?;
    fs::write(flake_dir.join("package.nix"), &package_nix)
        .with_context(|| format!("Failed to write package.nix for {}", project_name))?;

    Ok(2)
}

// ── JavaScript flake generation ─────────────────────────────────────────

/// Generate a JavaScript/Node.js flake using `buildNpmPackage`.
pub fn generate_js_flake(
    project_dir: &Path,
    output_dir: &Path,
    _style: FlakeStyle,
    source: &FlakeSource,
) -> Result<usize> {
    let project_name = project_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("js-project");
    let flake_dir = output_dir.join("flakes").join(&project_name);
    fs::create_dir_all(&flake_dir)
        .with_context(|| format!("Failed to create flake dir: {}", flake_dir.display()))?;

    let (src_input, src_attr) = match source {
        FlakeSource::LocalDir => (String::new(), String::new()),
        FlakeSource::GitMirror { mirror_path, display: _ } => {
            let input = format!(
                r#"    src = {{
      url = "git+file://{mirror}";
      flake = false;
    }};
"#,
                mirror = mirror_path.display()
            );
            (input, "src".to_string())
        }
    };

    let params = if src_attr.is_empty() {
        "{ self, nixpkgs, flake-utils }".to_string()
    } else {
        format!("{{ self, nixpkgs, flake-utils, {src_attr} }}")
    };

    let src_reference = if src_attr.is_empty() {
        "./.".to_string()
    } else {
        format!("{src_attr}")
    };

    let package_nix = format!(
        r#"{{ pkgs, lib, src ? ./., ... }}:

pkgs.buildNpmPackage {{
  pname = "{name}";
  version = "0.1.0";
  inherit src;
  npmDeps = pkgs.fetchNpmDeps {{
    inherit src;
    hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";  # set after first build
  }};
  npmBuildScript = "build";
  npmBuildInputs = with pkgs; [ ];
  dontNpmBuild = false;
  doCheck = false;
}}
"#,
        name = project_name
    );

    let flake_nix = format!(
        r#"# THIS FILE IS AUTO-GENERATED by cargo-vendormod (JavaScript)
# DO NOT EDIT MANUALLY
#
# Package: {name}

{{
  description = "{name} - JavaScript package";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
{src_input}  }};

  outputs =
    {params}:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {{ inherit system; }};
        real_src = {src_reference};
      in
      {{
        packages = {{
          default = pkgs.callPackage ./package.nix {{ src = real_src; }};
          {name} = self.packages.${{system}}.default;
        }};

        devShells.default = pkgs.mkShell {{
          buildInputs = with pkgs; [ nodejs nodePackages.npm ];
        }};
      }}
    );
}}
"#,
        name = project_name,
        src_input = src_input,
        params = params,
        src_reference = src_reference,
    );

    fs::write(flake_dir.join("flake.nix"), &flake_nix)
        .with_context(|| format!("Failed to write flake.nix for {}", project_name))?;
    fs::write(flake_dir.join("package.nix"), &package_nix)
        .with_context(|| format!("Failed to write package.nix for {}", project_name))?;

    Ok(2)
}

// ── Java flake generation ───────────────────────────────────────────────

/// Generate a Java flake using `stdenv.mkDerivation` with Maven.
pub fn generate_java_flake(
    project_dir: &Path,
    output_dir: &Path,
    _style: FlakeStyle,
    source: &FlakeSource,
) -> Result<usize> {
    let project_name = project_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("java-project");
    let flake_dir = output_dir.join("flakes").join(&project_name);
    fs::create_dir_all(&flake_dir)
        .with_context(|| format!("Failed to create flake dir: {}", flake_dir.display()))?;

    let (src_input, src_attr) = match source {
        FlakeSource::LocalDir => (String::new(), String::new()),
        FlakeSource::GitMirror { mirror_path, display: _ } => {
            let input = format!(
                r#"    src = {{
      url = "git+file://{mirror}";
      flake = false;
    }};
"#,
                mirror = mirror_path.display()
            );
            (input, "src".to_string())
        }
    };

    let params = if src_attr.is_empty() {
        "{ self, nixpkgs, flake-utils }".to_string()
    } else {
        format!("{{ self, nixpkgs, flake-utils, {src_attr} }}")
    };

    let src_reference = if src_attr.is_empty() {
        "./.".to_string()
    } else {
        format!("{src_attr}")
    };

    let has_maven = project_dir.join("pom.xml").exists();

    let (build_inputs, build_phase) = if has_maven {
        (
            "jdk maven",
            r#"    buildPhase = ''
      mvn package -DskipTests -Dmaven.repo.local=$TMPDIR/repository
    '';
    installPhase = ''
      mkdir -p $out/share/java
      cp target/*.jar $out/share/java/
    '';"#,
        )
    } else {
        (
            "jdk gradle",
            r#"    buildPhase = ''
      gradle build -x test
    '';
    installPhase = ''
      mkdir -p $out/share/java
      cp build/libs/*.jar $out/share/java/
    '';"#,
        )
    };

    let package_nix = format!(
        r#"{{ pkgs, lib, src ? ./., ... }}:

pkgs.stdenv.mkDerivation {{
  pname = "{name}";
  version = "0.1.0";
  inherit src;

  nativeBuildInputs = with pkgs; [ {build_inputs} ];

{build_phase}

  doCheck = false;
}}
"#,
        name = project_name,
        build_inputs = build_inputs,
        build_phase = build_phase,
    );

    let flake_nix = format!(
        r#"# THIS FILE IS AUTO-GENERATED by cargo-vendormod (Java)
# DO NOT EDIT MANUALLY
#
# Package: {name}

{{
  description = "{name} - Java package";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
{src_input}  }};

  outputs =
    {params}:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {{ inherit system; }};
        real_src = {src_reference};
      in
      {{
        packages = {{
          default = pkgs.callPackage ./package.nix {{ src = real_src; }};
          {name} = self.packages.${{system}}.default;
        }};

        devShells.default = pkgs.mkShell {{
          buildInputs = with pkgs; [ jdk maven ];
        }};
      }}
    );
}}
"#,
        name = project_name,
        src_input = src_input,
        params = params,
        src_reference = src_reference,
    );

    fs::write(flake_dir.join("flake.nix"), &flake_nix)
        .with_context(|| format!("Failed to write flake.nix for {}", project_name))?;
    fs::write(flake_dir.join("package.nix"), &package_nix)
        .with_context(|| format!("Failed to write package.nix for {}", project_name))?;

    Ok(2)
}

// ── Generic dispatcher ──────────────────────────────────────────────────

/// Dispatch flake generation to the appropriate language generator.
///
/// Uses `lang_detect::detect_language()` to auto-detect the project language.
/// Falls back to Rust if no recognized language is found.
pub fn generate_multi_lang_flake(
    project_dir: &Path,
    output_dir: &Path,
    style: FlakeStyle,
    source: &FlakeSource,
    lang_override: Option<crate::lang_detect::Language>,
    nora: bool,
) -> Result<usize> {
    let lang = lang_override
        .unwrap_or_else(|| crate::lang_detect::detect_language(project_dir));

    match lang {
        crate::lang_detect::Language::Rust => {
            crate::crate_flake::generate_flake(project_dir, output_dir, None, style, None, source.clone(), nora)
        }
        crate::lang_detect::Language::Go => {
            generate_go_flake(project_dir, output_dir, style, source)
        }
        crate::lang_detect::Language::Python => {
            generate_python_flake(project_dir, output_dir, style, source)
        }
        crate::lang_detect::Language::C => {
            generate_c_flake(project_dir, output_dir, style, source)
        }
        crate::lang_detect::Language::JavaScript => {
            generate_js_flake(project_dir, output_dir, style, source)
        }
        crate::lang_detect::Language::Java => {
            generate_java_flake(project_dir, output_dir, style, source)
        }
        crate::lang_detect::Language::Unknown => {
            // Fallback to Rust (default behavior)
            crate::crate_flake::generate_flake(project_dir, output_dir, None, style, None, source.clone(), nora)
        }
    }
}
