# THIS FILE IS AUTO-GENERATED by cargo-vendormod
# DO NOT EDIT MANUALLY — regenerate with:
#   cargo-vendormod process crates --generate-flakes
#
# Crate: ucan_wasm
# Version: 0.1.0

{
  description = "ucan_wasm - 0.1.0";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        real_src = ./.;
      in
      {
        packages = {
          default = pkgs.callPackage ./package.nix { src = real_src; };
          ucan_wasm = self.packages.${system}.default;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            rustc
            cargo
            clippy
            rustfmt
          ];
        };

        # Verification: nix flake check
        checks.default = self.packages.${system}.default;
      }
    );
}
